### ISSUE TITLE
react-native+ZipArchive demo

### ISSUE THREAD

**Issue by sany620** [plrthink/react-native-zip-archive#1]
Hope to upload a complete react-native to learn +ZipArchive demo

**Comment by plrthink** [comment]
@sany620 Yep, I would do that when I have time. Also need to add more features.

**Comment by plrthink** [comment]
@sany620 I find I have already put an example in README.md

```
ZipArchive.unzip(sourcePath, targetPath)
.then(() => {
  console.log('unzip completed!')
})
catch((error) => {
  console.log(error)
})
```

Currently, it just offers unzip functionality.

**Comment by plrthink** [comment]
@sany620 updated example in readme.

**Comment by rneiss** [comment]
+1 for this. I'm having trouble getting the code in the readme to work. 
Is there any chance you can upload a super basic project that demos this functionality?

**Comment by plrthink** [comment]
@rneiss there's mistake in the example :sweat_smile:, and I have just fixed that.

**Comment by rneiss** [comment]
Thanks. I'm still having trouble though. It's throwing a syntax error `unexpected token` at the start of the line where the catch routine is. 

Maybe I'm referencing the file incorrectly though. Is there a trick to adding and referencing the zip file that I'm missing?

**Comment by plrthink** [comment]
@rneiss Could you show paste the error message here?

**Comment by plrthink** [comment]
@rneiss I'm using this package to unzip my zip file downloaded by [react-native-file-download](https://github.com/plrthink/react-native-file-download), in which case I'm sure the file is in the path. 

I also use [react-native-fs](https://github.com/johanneslumpe/react-native-fs) to get access to file system as mentioned in README. So I am using `console.log(require('react-native-fs').DocumentDirectoryPath)` when develop and debug apps, since I downloaded zip file into that directory. So I guess that error occurs because the zip file doesn't exists at the path, you can try  "react-native-fs" to get things work. And also I should log more cleaner message about what errors happens:smile:

**Comment by rneiss** [comment]
@plrthink  -- the error message isn't actually all that helpful. The code never seems to actually make it to the console.log and chokes right at the catch statement: 

`2015-11-11 07:47:32.514 [error][tid:main][RCTBatchedBridge.m:436] Error while loading: SyntaxError [React Native App Dir]/index.ios.js: Unexpected token (52:1)`

I'm going to play with file system to see if that helps. Will report back. Thanks for your support regardless.

**Comment by rneiss** [comment]
ok -- so using react-native-fs I've managed to get it working, but only if I remove the catch statement from the js. Otherwise it still throws the same error as before.

So success![?]

Thanks for your help.

**Comment by plrthink** [comment]
@rneiss which version of react-native and iOS you are developing?

**Comment by plrthink** [comment]
@rneiss After double check api example in README, I found that there's still a typo. I missed a dot before `catch` statement. It should like:

```js
...
.catch((error) => {
  console.log(error)
})
```

This means it catch error threw by this package. Of course you can do anything in catch.

I should fix it in README.

**Comment by plrthink** [comment]
Since it's no longer active I am going to close this.
